### ISSUE TITLE
Type Validation fails on empty string even when not required 

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/cbvalidation#35]
The following property declaration:

```
   property name="email"
                type="string"
                ormtype="string"
                default="";
```

with the following validation rule:

```
"email"         : {
            "required"      : false,
            "type"          : "email"
}
```

Will throw an error because the empty strings are validate-able and even an explicit null casting still returns an empty string on the getter.

Suggestion:

- Igore empty strings for type validation when `required` is false
or
- Add an `ignoreEmpty` validation configuration option

**Comment by lmajano** [comment]
I have just hit this issue as well.  It is tricky, because, validators act independently of each other.  So in all reality, the type validaotr, or the `regex` validator, which is what I was using, was baically just trying to validate according to the data given.  It doesn't know about other validators in the execution phase.

So it is tricky to decide what should happen.  

If the required is true, then it should pick it up, If not true, it will allow empty to pass.  

So in reality, this should be accross the board for ALL validators, what to do on empty values? Do you simply ignore if null or empty?

**Comment by lmajano** [comment]
I can see a few options.

1) We can pass the constratints for the field as an argument to all validators as part of the packet. This will allow the validators to have the full struct of constraints decalred for the field.

2) If we do 1), then we could read the `required` key from the rules.

3) Add an `ignoreEmpty` but if you can read the `required` then maybe that doesn't make sense.

4) Forget all that, and if the incoming value is empty or null, just ignore accross the board.

**Comment by lmajano** [comment]
now completed
