### ISSUE TITLE
Existing, but empty, values fail `required` checks

### ISSUE THREAD

**Issue by davidAtInleague** [coldbox-modules/cbvalidation#54]
```
validateOrFail(constraints = {a: {required:true}}, target = {a: []}) // fails
validateOrFail(constraints = {a: {required:true}}, target = {a: [42]}) // passes
validateOrFail(constraints = {a: {required:true}}, target = {a: ""}) // fails
validateOrFail(constraints = {a: {required:true}}, target = {a: "42"}) // passes
```
I propose that all of the above should pass, because property `a` is present.

**Comment by lmajano** [comment]
This is complicated, because required usually denotes that a field Must have a non empty value assigned to it.  The majority of validation frameworks for many languages treat it as such.

However, we all know that every requirement is different.  In this case, I cannot change the behavior of an established validator to meet this requirement.  However, what you can do us a custom validator you can build and use: https://coldbox-validation.ortusbooks.com/advanced/advanced-custom-validators

This way, you can create your own concern and reuse it as you please.
